### ISSUE TITLE
Start namenode & datanode docker from Windows CMD issue || ./entrypoint.sh: /start-namenode.sh: /bin/bash^M: bad interpreter: No such file or directory 

### ISSUE THREAD

**Issue by EMagdi** [amhhaggag/bigdata-ecosystem-sandbox#1]
When running Docker from Windows CMD, the issue with Windows-style line endings (CRLF) might occur. 
And when checking the logs docker logs -f datanode after starting the docker, the below might appear
./entrypoint.sh: /start-namenode.sh: /bin/bash^M: bad interpreter: No such file or directory 

Here’s how you can handle it:
fastest way is to go to the start-namenode.sh located at docker\hadoop\hadoop-datanode through notepad ++ 
Edit > EOL Conversion > Unix (LF), and save the file.

This should resolve the bad interpreter error.

build and start again 
docker-compose build namenode
docker-compose up -d namenode

**Comment by amhhaggag** [comment]
Solved in the 2024-10-21 Release.
In this release we are not building the docker images of the namenode and datanode containers, instead we configured all the dependencies and the required commands in the main docker-compose.yml file.
