### ISSUE TITLE
Issue while inserting data into hive managed table 

### ISSUE THREAD

**Issue by EMagdi** [amhhaggag/bigdata-ecosystem-sandbox#2]
when inserting data into table after starting hive-server alone
the below error received related to history server

"Job Submission failed with exception 'java.io.IOException(Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.)'
java.io.IOException: Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: historyserver "

Can we add the following dependencies to the metastore container for example  : 
    depends_on:      
      - datanode     (datanode container depends already on namenode)
      - postgres
      - nodemanager
      - resourcemanager
      - historyserver

**Comment by amhhaggag** [comment]
added the dependencies in the docker-compose.yml file
